import type { Entry, ImageAsset } from "./types";

export const workHero = {
  title: "Things I've worked on",
  image: {
    src: "/images/work/hero.jpg",
    alt: "David at a standing desk in the Citrus office",
    width: 2000,
    height: 1332,
  } satisfies ImageAsset,
};

export const workEntries: Entry[] = [
  {
    slug: "offstreet",
    name: "Offstreet",
    years: "2025 - Present",
    logo: {
      src: "/images/work/offstreet-logo.png",
      alt: "Offstreet",
      width: 1500,
      height: 356,
    },
    banner: {
      src: "/images/work/offstreet-banner.png",
      alt: "Offstreet parking management dashboard",
      width: 1080,
      height: 995,
    },
    description: [
      "Offstreet helps universities and private operators simplify guest parking. Improve experiences, reduce manual work, and streamline operations with our flexible, easy-to-use parking solutions.",
    ],
    link: { label: "Visit Offstreet", href: "https://joinoffstreet.com/" },
    roleTitle: "My role at Offstreet…",
    role: [
      "Starting in the spring of 2025 as a Senior Software Developer, I was excited for the new challenge of a smaller team and big product goals.",
    ],
    learnedTitle: "Things I've learned…",
    learned: [
      "Strengthened my ability to operate autonomously on complex, ambiguous systems work, taking initiatives from planning through delivery and support.",
      "Developed a more pragmatic architectural mindset, balancing speed, risk, and long-term maintainability within a legacy codebase.",
      "Improved developer experience and platform health by proactively shipping internal tooling and DX improvements beyond assigned tickets.",
      "Deepened my ownership mindset by anticipating risks, handling migrations and on-call realities, and following through on outcomes.",
      "Learned where to further raise the bar in testing, regression coverage, and pre-ship feedback loops to deliver higher-confidence releases at scale.",
    ],
    workedOnTitle: "Things I worked on…",
    workedOn: [
      "Led the end-to-end tenant and location decoupling effort, spanning schema design, legacy + new APIs, UI, data migrations, permissions, and cleanup on a high-risk, long-running initiative.",
      "Designed and shipped type-safe abstractions across Prisma, TypeORM, and Kysely, improving correctness and maintainability despite weak legacy guarantees.",
      "Owned and executed production-safe data migrations (tenant transfer, tenant merge) with validation, dry runs, rollback awareness, and minimal operational risk.",
      "Stabilized and modernized legacy APIs while preserving backward compatibility, unblocking new architecture and future work.",
      "Consistently unblocked teams through test reliability improvements, firefighting production issues, and delivering complex UI flows that aligned frontend and backend behaviour.",
    ],
  },
  {
    slug: "sticker-mule",
    name: "Sticker Mule",
    years: "2024 - 2025",
    logo: {
      src: "/images/work/sticker-mule-logo.png",
      alt: "Sticker Mule",
      width: 1024,
      height: 141,
    },
    banner: {
      src: "/images/work/sticker-mule-banner.png",
      alt: "Sticker Mule stickers and packaging",
      width: 510,
      height: 330,
    },
    description: [
      "Thousands of people trust Sticker Mule to make kick ass stickers, labels, packaging & more. Free proofs, free worldwide shipping, fast turnaround & 24/7 customer support.",
    ],
    link: { label: "Visit Sticker Mule", href: "https://www.stickermule.com/" },
    roleTitle: "My role at Sticker Mule…",
    role: [
      "I joined on at Sticker Mule as a Backend Engineer, this would be my first role as an individual contributor after founding Citrus. It was first time working with a fully remote and distributed company.",
    ],
    learnedTitle: "Things I've learned…",
    learned: [
      "Working with GraphQL APIs at scale",
      "Ruby on Rails at an enterprise level as we migrated the large code base to Node services",
      "Maintaining optimal back-end performance",
      "Contributing safely to production daily through small changes",
    ],
    workedOnTitle: "Things I worked on…",
    workedOn: [
      "Engineered three high-utility Twitter/X bots with complex integrations and asynchronous operations",
      "Led improvements to the multi-artwork feature by overhauling cart logic, line item editing, and email templates",
      "Integrating Stimulus with Sticker Mule's systems",
      "Enhancing error handling and logging across different services.",
      "Implementing prefilling for the framed tweet form to streamline the user experience.",
    ],
  },
  {
    slug: "citrus",
    name: "Citrus",
    years: "2020 - 2024",
    logo: {
      src: "/images/work/citrus-logo.png",
      alt: "Citrus",
      width: 721,
      height: 205,
    },
    banner: {
      src: "/images/work/citrus-banner.png",
      alt: "Coach overwhelmed by all the things that they have to deal with",
      width: 1080,
      height: 1079,
    },
    description: [
      "Running a youth program isn't easy. Citrus handles your registrations, organizes customer information, and saves you time so you can focus on what really matters.",
    ],
    link: { label: "Visit Citrus", href: "https://www.citruscamps.com/" },
    roleTitle: "My role at Citrus…",
    role: [
      "As Chief Technology Officer, my responsibilities have been to oversee our internal technology needs as well as service the needs of the product. I have lead our team and have designed the user experience, build pipeline, infrastructure, and developer workflows for Citrus. For the past four years, I have taken our application from zero to sixty customers across Canada and US.",
    ],
    learnedTitle: "Things I've learned so far…",
    learned: [
      "Importance of frequent and continuous delivery",
      "Scaling NestJS and React applications with customer growth",
      "Power of feature flags and customer feedback",
      "Building Event-Driven Design services using queues",
      "Training and building knowledge base to accelerate junior developer growth",
      "Clustering Node.js applications with pm2",
      "Building a product roadmap that supports grow for the organization",
    ],
    workedOnTitle: "Things I worked on so far…",
    workedOn: [
      "Build pipelines in both AWS CodePipeline and GitHub Actions",
      "Running developer days / weeks to invoke creativity and accelerate knowledge growth",
      "Highly available payment services processing $10M over the last four years using Stripe Connect",
      "Privacy driven CRM built for families that isolates data to the owner",
      "Email campaign and inbox for communication with parents so they never miss a message",
      "Schedule payments with memberships that allow programs to create a relationship with attendees",
      "Online bookings that allow you to schedule 1 on 1 appointments based on your availability",
      "Low latency short link generator with analytics and the ability to generate a QR Code",
    ],
  },
  {
    slug: "toolshed",
    name: "Toolshed",
    years: "2019 - 2020",
    logo: {
      src: "/images/work/toolshed-logo.png",
      alt: "Toolshed",
      width: 1000,
      height: 230,
    },
    banner: {
      src: "/images/work/toolshed-banner.png",
      alt: "Demonstration of Toolshed on a laptop left of a mobile phone with the same screen.",
      width: 1920,
      height: 977,
    },
    description: [
      "Toolshed is an online application designed to help you rent and lend the tools that make DIY projects possible. Reducing the amount of unused tools and helping reducing costs for handy folks out there.",
    ],
    roleTitle: "My role at Toolshed…",
    role: [
      "Starting the company as the Chief Executive Officer, I was very passionate about this problem and it was my first experience within a startup. Although Toolshed failed, I learned plenty in expanding my development skills and the areas that require extra effort (marketing, sales, and finances). Within nine months, I attempted to evaluate the idea and successfully had three rentals within Regina.",
    ],
    learnedTitle: "Things I've learned…",
    learned: [
      "Great products still require marketing and sales, not all problems can be solved with features",
      "Startups are not easy on your own and require a well-balanced team to execute",
      "Talking with customers is important to any company or product development",
      "Deliver a three-minute pitch that communicates the value of the product to hundreds of people",
      "Building and deploying Express and Angular applications to AWS",
    ],
    workedOnTitle: "Things I worked on…",
    workedOn: [
      "Reducing friction within the platform and focusing on user experience",
      "Built and maintained an active business plan",
      "Building trust within our online community with Stripe Connect's payouts",
      "Product-led growth using discount and referral codes",
      "Providing insights to money earned lending and saved renting",
      "Ensuring privacy with geolocation masking when finding tools in your area",
      "Peer-to-peer chat using web sockets for instant updates",
      "Some light AI work with suggested pricing and generated tool descriptions based on images using AWS Rekognition",
    ],
  },
  {
    slug: "vivvo",
    name: "Vivvo",
    years: "2017 - 2019",
    logo: {
      src: "/images/work/vivvo-logo.png",
      alt: "Vivvo",
      width: 351,
      height: 52,
    },
    banner: {
      src: "/images/work/vivvo-banner.png",
      alt: "CitizenOne shown on a laptop mockup",
      width: 940,
      height: 788,
    },
    description: [
      "Enable the digital transformation of government services with CitizenOne. We've developed a platform that makes it easy for citizens to access, manage and use government services.",
    ],
    link: { label: "Visit Vivvo", href: "https://www.vivvo.com/" },
    roleTitle: "My role at Vivvo…",
    role: [
      "I originally joined as a Software Developer and eventually moved into the role Product Team Lead. Vivvo allowed me to flexible both my business and development skills. I led a few projects from the gathering of requirements, customer meetings, budget tracking, leading sprints, and developing new features. I was fortunate to work with many talented individuals on some impactful projects.",
    ],
    learnedTitle: "Things I've learned…",
    learned: [
      "Running one on ones to help my team fulfill their goals with the vision of the company",
      "Efficiently collecting and reporting time with a budget and list of deliverables",
      "Deploying once every six months can lead to not so fun late nights",
      "Building and working within Spring Boot applications",
      "Good leadership is important for a company to grow and retain talent",
    ],
    workedOnTitle: "Things I worked on…",
    workedOn: [
      "Verifying and connecting your Saskatchewan business to access government services",
      "Implementing an OAuth handshake to access eHealth data",
      "Upgrading front-end applications from Angular.js to Angular",
      "Designing and developing the government administrative application",
      "Enabling integrations through improving API stability and documentation",
    ],
  },
  {
    slug: "iqmetrix",
    name: "iQmetrix",
    years: "2015 - 2017",
    logo: {
      src: "/images/work/iqmetrix-logo.png",
      alt: "iQmetrix",
      width: 2500,
      height: 548,
    },
    banner: {
      src: "/images/work/iqmetrix-banner.png",
      alt: "Many screens layered expanding to the right of tablet",
      width: 1420,
      height: 1055,
    },
    description: [
      "Streamlined retail management, point-of-sale, unified commerce, and device activation solutions that simplify telecom retail, delivering a seamless and uplifting experience for your business and customers.",
    ],
    link: { label: "Visit iQmetrix", href: "https://www.iqmetrix.com/" },
    roleTitle: "My role at iQmetrix…",
    role: [
      "Starting as co-op student in technical support, I eventually moved into development primarily focusing on web development. After graduation, I joined full-time as a Software Developer working on an administrator web application for iQmetrix's point of sale targeted at general retail and dispensaries, which would eventually become Cova. It was around this point I was wanting to flex my program management skills by helping guide sprints, build requirements, and worked closely with the design team in my new role Business Analyst.",
    ],
    learnedTitle: "Things I've learned…",
    learned: [
      "Generalists typically don't work at larger organizations, but there is always room for growth",
      "Successfully transitioning responsibilities when moving out of one role into another",
      "Software development lifecycle for both mobile, web and API services",
      "Building applications with .NET and Marionette.js",
      "Working with a design system",
    ],
    workedOnTitle: "Things I worked on…",
    workedOn: [
      "Creating and managing a companies general ledger accounts",
      "Searching, creating, and manage contact details within a CRM",
      "Gather requirements and implementing methods to manage taxes for products and locations",
      "Researching and constructing user stories for batch tracking and inventory with cannabis suppliers",
      "Investigating cannabis delivery and fit within our point of sale product",
    ],
  },
];
